#pragma config(Sensor, S1,     colorSensorLeft, sensorI2CCustom)
#pragma config(Sensor, S2,     colorSensorMiddle, sensorLightActive)
#pragma config(Sensor, S3,     colorSensorRight, sensorI2CCustom)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includings/spurenerkennung.h"
#include "includings/variablen.h"
#include "includings/move.h"

task main()
{
	while(true) {
		RefreshColor();
		FollowLine(20);
	}
}
